### ISSUE TITLE
Minimum validator stake should be 3,175,000 FTM

### ISSUE THREAD

**Issue by MKong** [Fantom-foundation/fantom-sfc#1]
Currently, the minimum amount that a validator can stake is 1 FTM:

   `uint256 public constant minValidationStake = 1e18;`

However, the minimum amount that a validator must stake at any one time is 3,175,000 FTM, so the code should be:

   `uint256 public constant minValidationStake = 3175000 * 1e18;`

**Comment by devintegral3** [comment]
Please see https://github.com/Fantom-foundation/fantom-sfc/commit/17527944ca8db85b155f3bbd2d783ce4a4bafa13#diff-ba60e51901d758d9176bfbe185e81477R8

**Comment by MKong** [comment]
`    uint256 public constant minDelegation = 1000 * 1e18;`

=> minimum delegation is 1 FTM, so it should be:

`    uint256 public constant minDelegation =  1e18;`

`    uint256 public constant minValidationStakeIncrease = minValidationStake / 100; `

=> minimum increase in stake is 1 FTM, so it should be:

`     uint256 public constant minValidationStakeIncrease = 1e18; `

**Comment by devintegral3** [comment]
Those changes were reversed in https://github.com/Fantom-foundation/fantom-sfc/commit/89a6aaa5eb762d89aeda82d9ba91684639a8ad1f#diff-ba60e51901d758d9176bfbe185e81477R17 , https://github.com/Fantom-foundation/fantom-sfc/commit/89a6aaa5eb762d89aeda82d9ba91684639a8ad1f#diff-ba60e51901d758d9176bfbe185e81477R21
