### ISSUE TITLE
Why `pragma solidity >=0.5.0 <=0.5.3;`?

### ISSUE THREAD

**Issue by MKong** [Fantom-foundation/fantom-sfc#2]
Why does the Solc compiler version have to between 0.5.0 and 0.5.3? Is there a specific reason for it?

**Comment by devintegral3** [comment]
Version for unit tests (using truffle) and for node are compiled with different compilers. Truffle supports only 0.5.12 now (and 0.5.0 back then), which was the reason for this versions range

**Comment by devintegral3** [comment]
I'll update it to 0.5.12 only in one of next PRs. Do you agree?

**Comment by MKong** [comment]
Okay sounds good.
